const router = require("express").Router()
const ProjectController = require("../controllers/ProjectController")
const validateToken = require("../middleware/AuthMiddleware")
router.post("/", validateToken, ProjectController.createProject)
router.get("/", ProjectController.getAllProjects)
router.get("/:id", ProjectController.getProject)
router.put("/:id", ProjectController.updateProject)
router.delete("/:id", validateToken, ProjectController.deleteProject)
router.patch("/:id/status", ProjectController.changeProjectStatus)
module.exports = router