const router = require("express").Router()
const TaskController = require("../controllers/TaskController")
router.post("/create",TaskController.createTask)
router.get("/all",TaskController.getAllTasks)
router.get("/:id",TaskController.getTask)
router.put("/assign/:id",TaskController.assignTask)
router.put("/submit/:id",TaskController.submitTask)
router.put("/:id",TaskController.updateTask)
router.delete("/:id",TaskController.deleteTask)
module.exports=router